### ISSUE TITLE
[Lara Staking] Enhance test suite: Unit, fuzz and invariant testing

### ISSUE THREAD

**Issue by VargaElod23** [Lara-staking/liquid-staking#49]
There are two test files tackling (partially) the validity of the `veLARA` & `Lara Staking` logic:

1. LaraStaker.t.sol
2. veLara.t.sol

### veLARA and setup

The `veLARA` token is a vested reward token for LARA token stakers. This is the reward that users can claim for staking. 

It is used to offset the selling pressure on the LARA token and it's main purpose is for users to be able to redeem these `veLARA` tokens in the `Lara Staking contract` for LARA tokens. 

### Lara Staking Contract

The contract is built on the audited [thirdweb staking contract](https://thirdweb.com/thirdweb.eth/TokenStake), simplifying it for our use-case.

1. Users stake their `LARA` tokens
2. They can claim `veLARA` tokens
3. When they claim `veLaRA` tokens a claim is created for them
4. WHen they try to redeem `LARA` tokens by "giving the veLARA tokens back(burning them)", they get a linear percentage of TARA tokens based on how mature the claim was(if they wanna redeem 10k worth of `veLARA` rewards and they waited the full 6 months of maturity, they'll get 10k `LARA` tokens for their `veLARA`, if not, they'll get let's say 1/6 * 10k after a single month).

**TODO**

I added tests for the main use-cases => happy flow. We need to cover edge cases and unhappy flows or misuses.

- [ ] Add unit tests for corner cases of uints
- [ ] Check for proper overflow/underflows for methods that have loops
- [ ] Check the business logic to be entirely true(mini-audit)
- [ ] Add more unit & fuzz tests to cover unhappy flows
- [ ] Add more unit & fuzz tests to cover misuses or potential malicious behaviour
- [ ] Identify invariants(example: at any given time the total supply of `veLARA` needs to be the total given rewards + the balance of the staking contract) and add invariant tests.
